### ISSUE TITLE
Ship Crew Persist across Ships

### ISSUE THREAD

**Issue by WishingOnAWendy** [ryceg/Eigengrau-s-Essential-Establishment-Generator#149]
**Describe the bug**
When you go to a ship in the port and generate a crew member to meet if you then go back and go to another ship the crew member generated for the previous ship will still be there under "Meet one of the Crew"

**To Reproduce**
Have more than one ship in the docks, press "Meet one of the Crew" then go back and go to the other ship.

**Expected behavior**
When going to a different ship the "Meet one of the Crew" text should be reset to blank so that the same crewmember is not on multiple ships.

**Comment by ryceg** [comment]
This is tricky, because in other similar usecases (such as brothels), NPC persistence is useful because it ensures that if the user wants to return to a previous character that they used, it isn't lost. I'm not convinced that it's an _issue_ as such, because it's a relatively small bug that has little to no negative user experience, and leaving it in poses to be a decent QoL save. Thoughts?
