### ISSUE TITLE
Error occurs when removing faction mentioned in village description

### ISSUE THREAD

**Issue by Zalatos** [ryceg/Eigengrau-s-Essential-Establishment-Generator#260]
**Describe the bug**
error occurs on page aswell as in console when removing a faction mentioned in a writeup.
is there no way to assign positions or redefine them. perhaps a "reassign faction/npc" button in place of the error

**To Reproduce**
Go to village description page. remove mentioned faction (eg the town's needs are handled by ,Ms Piggins.. most of the day to responsibilities fall on [Jasper's carpenters] who is lead by <Bob Fogey>" click the x next to [Jasper's Caprenters] under the faction list and the error should occur) 

**Additional context**
i would love for a organogram to show how npcs fit all together

**Comment by ryceg** [comment]
Removing NPCs, factions, and buildings is currently very buggy, due to the nature of the way the town is procedurally generated. Thanks for highlighting this issue.

This is a rough sketch of how information is passed throughout the system; if you have an understanding of code, then you can easily follow the generator's source code like a breadcrumb trail, since they almost all involve passing objects as arguments linearly.

![image](https://user-images.githubusercontent.com/36913739/83100237-b8223200-a0f2-11ea-94d1-b5d5d1693e98.png)

**Comment by Zalatos** [comment]
thanks for the diagram

**Comment by ryceg** [comment]
Fixed in 813cbdb
