### ISSUE TITLE
Restructure createMagicWeapon arrays into objects.

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#309]
At the moment, `createMagicWeapon`, `createMagicArmour`, and `createMagicTrinket` all have the same structure; two properties, one of which takes the prefix, and the other the suffix to create the name of the item- e.g. 'Amethyst Padded Armour of the Woodlands', or 'Arboreal Padded Armour of Amethyst' are both the same.

These rely on the arrays being the same length for assigning the correct properties to the description. This is a Bad Idea.

Restructure into a single array of objects, with the properties of prefix, suffix, and the property.

**Comment by kimgb** [comment]
Picked out a 'good first issue' as this is my first venture into TypeScript, and I think I have a pull request for this, but my work has created some questions:
(1) are `createMagicWeapon.ts`, `createMagicArmour.ts`, `createMagicTrinket.ts` defunct, in favour of the more general pattern found in `createMagic.ts` et al? Can I safely delete them?
(2) in `magicData.data.json` should I combine the prefixes/suffixes/properties arrays into a single object array, or should I populate one object array each for prefixes and suffixes, so that prefixes and suffixes can have unique/divergent entries in the future?

**Comment by Glinkis** [comment]
Not sure about `1`,
But as for `2`, yes I think we should combine them. It's kind of iffy to have these arrays that need to be identical length to work properly. I think there is a separate issue for that already.

**Comment by ryceg** [comment]
Hi @kimgb, thanks for the (anticipated) pull request!
1. Yes.
2. I think that it's preferable to combine prefix/suffix/properties into single objects, since there's no need for an identical string- if we need to edit the wording of a property in future, it'd be a pain to have to find it in two places. It's also relatively straightforward to add in a check for whether there's the appropriate suffix/prefix in the case of prefix-only abilities being added.
