### ISSUE TITLE
Footer is not showing up

### ISSUE THREAD

**Issue by ryceg** [ryceg/Eigengrau-s-Essential-Establishment-Generator#328]
For reasons unknown, the footer doesn't want to show up. It's likely a CSS issue. It should extend from the left most part of the "page" that is visible (i.e. where the sidebar meets the page), to the right of the screen.

**Comment by Si-Alm** [comment]
I can look into this issue if you want.

**Comment by WishingOnAWendy** [comment]
> I can look into this issue if you want.

Go for it!

**Comment by Si-Alm** [comment]
I don't think I'll actually edit anything for this issue, since I don't know how Twine works. Just checking it out real quick, it looks like the footer's parent element is the "passage-start" div, but seems like it should be the "passages" div. For the CSS, there's no height defined for the footer which is why I think it isn't showing up. Good luck!

**Comment by ryceg** [comment]
That does it! Thanks.
