### ISSUE TITLE
npc information not loading

### ISSUE THREAD

**Issue by mickeymousez321** [ryceg/Eigengrau-s-Essential-Establishment-Generator#345]
the NPC page has a lot of the information with error codes. the information just will not load. I'm not sure how to fix the issue.

https://eigengrausgenerator.com/#sereneoldlacesilverfish

go to town description, click the name of the town leader it gives the basic information everything except her background, her finances and relationship. this issue happens for any character page I try. 
![SharedScreenshot](https://user-images.githubusercontent.com/67872888/95029120-02ed2100-0674-11eb-8afc-1027a63065aa.jpg)

**Comment by ryceg** [comment]
I'm unable to replicate this; https://eigengrausgenerator.com/#sereneoldlacesilverfish gets a village named Drunhamm. Can you please outline the exact steps to reproduce the bug (this includes any actions such as creating new buildings, renaming, or editing the town). If it is replicable then I will re-open the issue, as I have not encountered this particular error before.

**Comment by mickeymousez321** [comment]
i changed the population to 930 and changed the village to a theogratic primistic anarchy 
i removed all the buildings and created a market and tavern 2 shops and temple and a dungeon/jail
i created 3 factions 1thief,1 clergy and 1 merchant 
i believe thats all i changed when i went to the town leader it was an error and now all NPC have error for alot of the data

**Comment by mickeymousez321** [comment]
![SharedScreenshot2](https://user-images.githubusercontent.com/67872888/95033089-f4f6ca80-068a-11eb-9dc0-ea6b816ac497.jpg)

**Comment by mickeymousez321** [comment]
new error messsage appeared as well

**Comment by ryceg** [comment]
Can you please tell me whether you have the `Show town biome prompt upon restart?` setting toggled on? Is that how you are editing the town? Or are you editing it after generation? Eigengrau's Generator uses PRNG, which means that the results on the same seed are always going to be the same *if you replicate the steps exactly*. The town generates with the name "Drunhamm" and there's no step provided where this is accounted for. I am unable to locate the NPC Valanthe.

If you are trying for specific results and do not have the `Show town biome prompt upon restart` setting toggled on, I would suggest that you do that rather than delete buildings. Restarting with a different seed will also yield totally different results, if this ends up being an isolated issue with this specific seed.

**Comment by mickeymousez321** [comment]
i had turned it on if i make a new town it should load properly?

**Comment by ryceg** [comment]
Using a different seed will yield different results. Just hit restart and you'll come across a different town.

**Comment by mickeymousez321** [comment]
well theres a different error message on it now but it has all the info

**Comment by ryceg** [comment]
That doesn't help me diagnose the issue at all.

**Comment by mickeymousez321** [comment]
![SharedScreenshot3](https://user-images.githubusercontent.com/67872888/95036038-b239f000-0694-11eb-8cea-3efb67d6e910.jpg)

**Comment by mickeymousez321** [comment]
i turned that setting off and hit restart i just opened the town leader and thats the error message on the page
