### ISSUE TITLE
BMI Two Dimensional Array needs additional entries

### ISSUE THREAD

**Issue by SobranDM** [ryceg/Eigengrau-s-Essential-Establishment-Generator#478]
The BMI _calculation_ appears to be correct, as near as I can tell. However, what that BMI result translates to appears to be inaccurate. For example, I had a character that was 5'7" and 136 pounds listed at 21 BMI. Assuming there is some rounding going on, that is accurate--the actual BMI calculates out to 21.3.

However, while 21.3 falls smack in the middle of the **Normal** range for BMI, the character is listed as **Overweight**.

**Comment by ryceg** [comment]
Thanks- looks like the BMI descriptions (which are a two dimensional array of muscle mass vs bmi) skimp out on the lower end of descriptions. Will look into this.

**Comment by ryceg** [comment]
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/master/lib/npc-generation/bmiDescriptions.data.json

So, turns out that we're missing the lower end of BMI descriptions rather severely- much like the religiosity, this is a two dimensional array of BMI vs muscle mass (read: strength, going up to 20), which is in dire need of filling out.
