### ISSUE TITLE
Become more setting and system agnostic - no deity names.

### ISSUE THREAD

**Issue by PonyFlare** [ryceg/Eigengrau-s-Essential-Establishment-Generator#52]
**Is your feature request related to a problem? Please describe.**
One encounter I generated had a shrine of Moradin, which annoyed me a bit.
I so far haven't encountered anything else that was FR or 5e specific.

**Describe the solution you'd like**
Have an aspect of the deity instead. ie: "Shrine dedicated to the god of dwarves" or maybe even "an earth god" or "a god of smithing"

**Describe alternatives you've considered**
Look up what [insert FR deity] is about and figure out most appropriate alternative from the setting I'm using. Or just pick a random one.

**Comment by ryceg** [comment]
Thanks for this. This is a design philosophy question that I have been wrestling with since I started the generator. I maintain a level of setting and system agnosticism, but decided that the specific Gods would be more useful to DMs than a system agnostic. The Generator is built with the assumption that DMs are going to be reading a sentence ahead, correcting and customising the outputted text to suit their own needs. In this case, I decided that there was more to be gained from referencing specific gods; if the god clashes with a setting, the DM can just substitute their own generic. I hope that that helps explain my thought process.
