### ISSUE TITLE
Add random buildings

### ISSUE THREAD

**Issue by Kurohyou** [ryceg/Eigengrau-s-Essential-Establishment-Generator#677]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It'd be nice to be able to select random as an option in the add building selection. In addition, being able to select random [some subsection of building types] would be great. Some subtypes I could see would be:
- Random store
- Random manufactory/creator
- Random religious
- Random city building (jail, townhall, etc)

**Describe alternatives you've considered**

**Additional context**

**Comment by ryceg** [comment]
Hi! Thanks for the issue. 

The generator performs a bunch of calculations and dice rolls to figure out what to include upon start up; obviously it can't predict exactly what people want, though, which is why we have the option of specifying what building to forcibly add. 

This suggested feature sort of goes against that methodology of letting the generator do its thing _or_ let the user specify with perfect control. It is, after all, a DM tool first and foremost, and DMs are unlikely to want a random city building- they'll have a specific idea for what building they want. I hope that this explains why I am closing this issue.
